baseURL = "https://at.shoogle.net"
languageCode = "de"
title = "Österreich"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
