baseURL = "https://ar.shoogle.net/"
languageCode = "es"
title = "Argentina"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
