baseURL = "https://mx.shoogle.net/"
languageCode = "es"
title = "México"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
