baseURL = "https://bo.shoogle.net/"
languageCode = "es"
title = "Bolivia"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
