baseURL = "https://ci.shoogle.net"
languageCode = "fr"
title = "Côte d'Ivoire"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
