baseURL = "https://ie.shoogle.net"
languageCode = "en"
title = "Ireland and Northern Ireland"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
