baseURL = "https://de.shoogle.net/"
languageCode = "de"
title = "Deutschland"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
