[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.76.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/baden-wuerttemberg/*"
  to = "https://ln-baden-wuerttemberg.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/bayern/*"
  to = "https://ln-bayern.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/brandenburg/*"
  to = "https://ln-brandenburg.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/bremen/*"
  to = "https://ln-bremen.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/hamburg/*"
  to = "https://ln-hamburg.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/hessen/*"
  to = "https://ln-hessen.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/mecklenburg-vorpommern/*"
  to = "https://ln-mecklenburg-vorpommern.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/niedersachsen/*"
  to = "https://ln-niedersachsen.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/nordrhein-westfalen/*"
  to = "https://ln-nordrhein-westfalen.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/rheinland-pfalz/*"
  to = "https://ln-rheinland-pfalz.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/saarland/*"
  to = "https://ln-saarland.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/sachsen/*"
  to = "https://ln-sachsen.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/sachsen-anhalt/*"
  to = "https://ln-sachsen-anhalt.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/schleswig-holstein/*"
  to = "https://ln-schleswig-holstein.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/thueringen/*"
  to = "https://ln-thueringen.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/oesterreich/*"
  to = "https://ln-oesterreich.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/schweiz/*"
  to = "https://ln-schweiz.netlify.com/:splat"
  status = 200
