[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.76.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/ireland-and-northern-ireland/*"
  to = "https://ln-ireland-and-northern-ireland.netlify.app/:splat"
  status = 200
