[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.76.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/england/*"
  to = "https://ln-england.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/scotland/*"
  to = "https://ln-scotland.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/wales/*"
  to = "https://ln-wales.netlify.app/:splat"
  status = 200
